# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProyectoFinal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProyectoFinal
  pod 'Firebase/Analytics','7.2-M1'
  pod 'Firebase/Auth','7.2-M1'
  pod 'Firebase/Firestore','7.2-M1'
  pod 'Firebase/Storage','7.2-M1'

end
